# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a14cd4ebd6f81411e6b6bb02fcedc9a9e2ac7a8bb26ac6b4cc49f165d65299bac4dc21ac073591b28f14f65c75a77fc5a0f61596759b457ca59aad4c70e5677f

test:
  secret_key_base: 336ae84b3c5333885e0596b13926c6804ee38b28894dffee3073e481216330b1dab2525027053cd64a1e2ceca04567a3e4f1cf040f1e0f347f2a0666fa41b554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
